begin;
select plan(20);
select has_table('public','referral_bonus_grants','bonus grants exist');
select has_table('public','analysis_attempts','immutable analysis attempts exist');
select col_is_unique('public','referral_bonus_grants','user_id','an account receives one referral grant');
select col_is_unique('public','referral_bonus_grants','qualifying_transaction_id','a payment qualifies one grant');
select col_is_unique('public','analysis_attempts','reservation_id','each reservation owns one attempt');
select col_type_is('public','analysis_credit_reservations','funding_source','text','reservation funding is explicit');
select has_column('public','analysis_credit_reservations','bonus_grant_id','bonus-funded reservation references its grant');
select has_column('public','analysis_credit_reservations','period_start','reservation period is immutable');
select has_column('public','analysis_credit_reservations','period_end','reservation period end is immutable');
select has_function('public','get_referral_bonus_access_for_user',array['uuid'],'bonus access snapshot exists');
select has_function('public','start_analysis_attempt',array['uuid','uuid','uuid'],'attempt-bound start exists');
select like(pg_get_functiondef('public.start_analysis_attempt(uuid,uuid,uuid)'::regprocedure),'%ANALYSIS_ATTEMPT_SUPERSEDED%','attempt start rejects stale workers');
select unlike(pg_get_functiondef('public.start_analysis_attempt(uuid,uuid,uuid)'::regprocedure),'%min(attempt.id)%','legacy attempt fallback uses a supported UUID aggregate');
select has_function('public','project_revenuecat_transaction',array['text','uuid','text','text','text','text','text','text','text','timestamp with time zone','timestamp with time zone','timestamp with time zone','numeric','text','text','numeric','numeric','timestamp with time zone','timestamp with time zone'],'atomic transaction reward projection exists');
select like(pg_get_functiondef('public.reserve_analysis_credit_for_user(uuid,text,text,uuid)'::regprocedure),'%funding_source=''base''%','base allowance is consumed before bonus');
select like(pg_get_functiondef('public.reserve_analysis_credit_for_user(uuid,text,text,uuid)'::regprocedure),'%funding_source=''referral_bonus''%','analyses 11 through 13 can use the bonus grant');
select like(pg_get_functiondef('public.reconcile_analysis_credit_for_session(uuid)'::regprocedure),'%active_attempt_id%','terminal reconciliation uses exact attempt ownership');
select like(pg_get_functiondef('public.project_revenuecat_transaction(text,uuid,text,text,text,text,text,text,text,timestamp with time zone,timestamp with time zone,timestamp with time zone,numeric,text,text,numeric,numeric,timestamp with time zone,timestamp with time zone)'::regprocedure),'%state=''revoked''%','refund revocation removes unused bonus access');
select like(pg_get_functiondef('public.project_revenuecat_transaction(text,uuid,text,text,text,text,text,text,text,timestamp with time zone,timestamp with time zone,timestamp with time zone,numeric,text,text,numeric,numeric,timestamp with time zone,timestamp with time zone)'::regprocedure),'%revoked_at=null%','verified reversal restores only the same grant');
select like(pg_get_functiondef('public.project_revenuecat_transaction(text,uuid,text,text,text,text,text,text,text,timestamp with time zone,timestamp with time zone,timestamp with time zone,numeric,text,text,numeric,numeric,timestamp with time zone,timestamp with time zone)'::regprocedure),'%v_referral.reward_eligible%','only accounts with locked reward eligibility receive a first-payment reward');
select * from finish();
rollback;
