insert into public.exercises (id, slug, name, category) values
  (1, 'barbell-bench-press', 'Barbell Bench Press', 'Chest'),
  (2, 'incline-dumbbell-press', 'Incline Dumbbell Press', 'Chest'),
  (3, 'dumbbell-bench-press', 'Dumbbell Bench Press', 'Chest'),
  (4, 'incline-barbell-bench-press', 'Incline Barbell Bench Press', 'Chest'),
  (5, 'push-up', 'Push-Up', 'Chest'),
  (6, 'machine-chest-press', 'Machine Chest Press', 'Chest'),
  (7, 'cable-fly', 'Cable Fly', 'Chest'),
  (8, 'conventional-deadlift', 'Conventional Deadlift', 'Back'),
  (9, 'lat-pulldown', 'Lat Pulldown', 'Back'),
  (10, 'pull-up', 'Pull-Up', 'Back'),
  (11, 'seated-cable-row', 'Seated Cable Row', 'Back'),
  (12, 'one-arm-dumbbell-row', 'One-Arm Dumbbell Row', 'Back'),
  (13, 'barbell-bent-over-row', 'Barbell Bent-Over Row', 'Back'),
  (14, 'chest-supported-row', 'Chest-Supported Row', 'Back'),
  (15, 'face-pull', 'Face Pull', 'Back'),
  (16, 'romanian-deadlift', 'Romanian Deadlift', 'Legs'),
  (17, 'back-squat', 'Back Squat', 'Legs'),
  (18, 'front-squat', 'Front Squat', 'Legs'),
  (19, 'goblet-squat', 'Goblet Squat', 'Legs'),
  (20, 'leg-press', 'Leg Press', 'Legs'),
  (21, 'bulgarian-split-squat', 'Bulgarian Split Squat', 'Legs'),
  (22, 'walking-lunge', 'Walking Lunge', 'Legs'),
  (23, 'reverse-lunge', 'Reverse Lunge', 'Legs'),
  (24, 'leg-extension', 'Leg Extension', 'Legs'),
  (25, 'seated-leg-curl', 'Seated Leg Curl', 'Legs'),
  (26, 'hip-thrust', 'Hip Thrust', 'Legs'),
  (27, 'standing-calf-raise', 'Standing Calf Raise', 'Legs'),
  (28, 'barbell-overhead-press', 'Barbell Overhead Press', 'Shoulders'),
  (29, 'dumbbell-shoulder-press', 'Dumbbell Shoulder Press', 'Shoulders'),
  (30, 'dumbbell-lateral-raise', 'Dumbbell Lateral Raise', 'Shoulders'),
  (31, 'dumbbell-front-raise', 'Dumbbell Front Raise', 'Shoulders'),
  (32, 'rear-delt-fly', 'Rear-Delt Fly', 'Shoulders'),
  (33, 'upright-row', 'Upright Row', 'Shoulders'),
  (34, 'dumbbell-shrug', 'Dumbbell Shrug', 'Shoulders'),
  (35, 'standing-dumbbell-curl', 'Standing Dumbbell Curl', 'Arms'),
  (36, 'hammer-curl', 'Hammer Curl', 'Arms'),
  (37, 'barbell-curl', 'Barbell Curl', 'Arms'),
  (38, 'cable-curl', 'Cable Curl', 'Arms'),
  (39, 'preacher-curl', 'Preacher Curl', 'Arms'),
  (40, 'cable-triceps-pushdown', 'Cable Triceps Pushdown', 'Arms'),
  (41, 'overhead-triceps-extension', 'Overhead Triceps Extension', 'Arms'),
  (42, 'skull-crusher', 'Skull Crusher', 'Arms'),
  (43, 'parallel-bar-dip', 'Parallel-Bar Dip', 'Arms'),
  (44, 'close-grip-bench-press', 'Close-Grip Bench Press', 'Arms'),
  (45, 'front-plank', 'Front Plank', 'Core'),
  (46, 'side-plank', 'Side Plank', 'Core'),
  (47, 'crunch', 'Crunch', 'Core'),
  (48, 'hanging-leg-raise', 'Hanging Leg Raise', 'Core'),
  (49, 'cable-crunch', 'Cable Crunch', 'Core'),
  (50, 'ab-wheel-rollout', 'Ab Wheel Rollout', 'Core')
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  category = excluded.category,
  is_active = true;
