import { createServerClient } from "@supabase/ssr"; import { createClient } from "@supabase/supabase-js"; import { cookies } from "next/headers";
import type { DashboardFilters } from "./dashboard-filters"; import { loadAdminDashboard } from "./load-dashboard";
function required(name: string, fallbacks: string[] = []): string { for (const key of [name, ...fallbacks]) { const value = process.env[key]?.trim(); if (value) return value; } throw new Error(`Missing ${name}`); }
export function supabaseUrl() { return required("NEXT_PUBLIC_SUPABASE_URL", ["SUPABASE_URL", "EXPO_PUBLIC_SUPABASE_URL"]); }
export function supabaseAnonKey() { return required("NEXT_PUBLIC_SUPABASE_ANON_KEY", ["SUPABASE_ANON_KEY", "EXPO_PUBLIC_SUPABASE_ANON_KEY"]); }
export async function createCookieClient() { const store = await cookies(); return createServerClient(supabaseUrl(), supabaseAnonKey(), { cookies: { getAll: () => store.getAll(), setAll: (values) => { for (const { name, value, options } of values) try { store.set(name, value, { ...options, httpOnly: true, sameSite: "lax", secure: process.env.NODE_ENV === "production", path: "/", maxAge: Math.min(typeof options.maxAge === "number" ? options.maxAge : 28_800, 28_800) }); } catch { /* server component */ } } } }); }
export async function loadRuntimeAdminDashboard(filters: DashboardFilters = { window: "30d", exerciseId: null }) {
  const authClient = await createCookieClient(); const admin = createClient(supabaseUrl(), required("SUPABASE_SERVICE_ROLE_KEY"), { auth: { persistSession: false, autoRefreshToken: false } });
  return loadAdminDashboard({ getAuthenticatedEmail: async () => { const { data, error } = await authClient.auth.getUser(); return error ? null : data.user?.email ?? null; }, getSnapshot: async (selected) => { const { data, error } = await admin.rpc("get_founder_dashboard_snapshot_v2", { p_window: selected.window, p_exercise_id: selected.exerciseId }); if (error) throw new Error("Founder reporting query failed"); return data; } }, process.env.FORMIE_ADMIN_EMAIL, filters);
}
