-- Bound section detail queries by the same half-open interval as headline
-- metrics. This prevents historical custom ranges from including later rows.
create or replace function public.get_founder_business_dashboard_v8(
  p_section text default 'overview',p_window text default '30d',p_start date default null,p_end date default null
) returns jsonb language plpgsql security definer set search_path='' as $$
declare result jsonb; growth jsonb; start_at timestamptz; end_at timestamptz; item jsonb; rows jsonb:='[]'::jsonb; creator_id uuid;
begin
  if current_user not in ('postgres','service_role') then raise exception 'UNAUTHORIZED'; end if;
  result:=public.get_founder_business_dashboard_v7(p_section,p_window,p_start,p_end);
  start_at:=coalesce((result->>'rangeStart')::timestamptz,'-infinity'::timestamptz);
  end_at:=(result->>'rangeEnd')::timestamptz;

  for item in select value from jsonb_array_elements(coalesce(result->'creators','[]'::jsonb)) loop
    creator_id:=(item->>'id')::uuid;
    item:=jsonb_set(item,'{visits}',to_jsonb((select count(*) from public.referral_visits visit join public.creator_links link on link.id=visit.creator_link_id where link.creator_id=creator_id and visit.environment='production' and visit.issued_at>=start_at and visit.issued_at<end_at)));
    item:=jsonb_set(item,'{recovered}',to_jsonb((select count(*) from public.referral_visits visit join public.creator_links link on link.id=visit.creator_link_id where link.creator_id=creator_id and visit.environment='production' and visit.recovered_at>=start_at and visit.recovered_at<end_at)));
    item:=jsonb_set(item,'{pendingVisits}',to_jsonb((select count(*) from public.referral_visits visit join public.creator_links link on link.id=visit.creator_link_id where link.creator_id=creator_id and visit.environment='production' and visit.issued_at>=start_at and visit.issued_at<end_at and visit.claimed_at is null and visit.expires_at>end_at and visit.excluded_reason is null)));
    item:=jsonb_set(item,'{expiredUnmatchedVisits}',to_jsonb((select count(*) from public.referral_visits visit join public.creator_links link on link.id=visit.creator_link_id where link.creator_id=creator_id and visit.environment='production' and visit.issued_at>=start_at and visit.issued_at<end_at and visit.claimed_at is null and visit.expires_at<=end_at and visit.excluded_reason is null)));
    item:=jsonb_set(item,'{accounts}',to_jsonb((select count(*) from public.account_referrals referral where referral.creator_id=creator_id and referral.environment='production' and referral.attributed_at>=start_at and referral.attributed_at<end_at and not exists(select 1 from public.business_test_accounts test where test.user_id=referral.user_id))));
    item:=jsonb_set(item,'{paid}',to_jsonb((select count(*) from public.account_referrals referral where referral.creator_id=creator_id and referral.environment='production' and referral.attributed_at>=start_at and referral.attributed_at<end_at and not exists(select 1 from public.business_test_accounts test where test.user_id=referral.user_id) and exists(select 1 from public.subscription_transactions transaction where transaction.user_id=referral.user_id and transaction.environment='PRODUCTION' and transaction.gross_amount>0 and coalesce(transaction.purchased_at,transaction.created_at)<end_at))));
    item:=jsonb_set(item,'{commission}',to_jsonb(coalesce((select sum(entry.amount) from public.creator_commission_entries entry where entry.creator_id=creator_id and entry.currency='USD' and entry.created_at>=start_at and entry.created_at<end_at and not exists(select 1 from public.business_test_accounts test where test.user_id=entry.referred_user_id)),0)));
    item:=jsonb_set(item,'{bonusRecipients}',to_jsonb((select count(*) from public.referral_bonus_grants grant_row join public.account_referrals referral on referral.user_id=grant_row.user_id where referral.creator_id=creator_id and referral.environment='production' and grant_row.granted_at>=start_at and grant_row.granted_at<end_at and not exists(select 1 from public.business_test_accounts test where test.user_id=grant_row.user_id))));
    item:=jsonb_set(item,'{bonusGranted}',to_jsonb(coalesce((select sum(grant_row.units_granted) from public.referral_bonus_grants grant_row join public.account_referrals referral on referral.user_id=grant_row.user_id where referral.creator_id=creator_id and referral.environment='production' and grant_row.granted_at>=start_at and grant_row.granted_at<end_at and not exists(select 1 from public.business_test_accounts test where test.user_id=grant_row.user_id)),0)));
    item:=jsonb_set(item,'{bonusUsed}',to_jsonb((select count(*) from public.analysis_credit_reservations reservation join public.referral_bonus_grants grant_row on grant_row.id=reservation.bonus_grant_id join public.account_referrals referral on referral.user_id=grant_row.user_id where referral.creator_id=creator_id and referral.environment='production' and reservation.status='committed' and reservation.committed_at>=start_at and reservation.committed_at<end_at and not exists(select 1 from public.business_test_accounts test where test.user_id=grant_row.user_id))));
    item:=jsonb_set(item,'{bonusAiCost}',to_jsonb(coalesce((select sum(telemetry.estimated_cost_usd) from public.model_call_telemetry telemetry join public.analysis_attempts attempt on attempt.id=telemetry.analysis_attempt_id join public.analysis_credit_reservations reservation on reservation.id=attempt.reservation_id join public.referral_bonus_grants grant_row on grant_row.id=reservation.bonus_grant_id join public.account_referrals referral on referral.user_id=grant_row.user_id where referral.creator_id=creator_id and referral.environment='production' and telemetry.created_at>=start_at and telemetry.created_at<end_at and not exists(select 1 from public.business_test_accounts test where test.user_id=grant_row.user_id)),0)));
    rows:=rows||jsonb_build_array(item);
  end loop;
  result:=jsonb_set(result,'{creators}',rows);

  growth:=coalesce(result->'growth','{}'::jsonb);
  growth:=jsonb_set(growth,'{selfReported}',public.business_suppress_small_groups((select coalesce(jsonb_agg(jsonb_build_object('label',self_reported_source,'users',users)),'[]'::jsonb) from (select self_reported_source,count(*) users from public.onboarding_reporting_snapshots where completed_at>=start_at and completed_at<end_at group by self_reported_source) grouped)));
  growth:=jsonb_set(growth,'{verifiedAcquisition}',public.business_suppress_small_groups((select coalesce(jsonb_agg(jsonb_build_object('label',label,'users',users)),'[]'::jsonb) from (select case when referral.user_id is not null then 'creator_referral' else snapshot.self_reported_source end label,count(*) users from public.onboarding_reporting_snapshots snapshot left join public.account_referrals referral on referral.user_id=snapshot.user_id and referral.environment='production' and referral.attributed_at<end_at where snapshot.completed_at>=start_at and snapshot.completed_at<end_at group by 1) grouped)));
  growth:=jsonb_set(growth,'{ageRanges}',public.business_suppress_small_groups((select coalesce(jsonb_agg(jsonb_build_object('label',age_range,'users',users)),'[]'::jsonb) from (select age_range,count(*) users from public.onboarding_reporting_snapshots where completed_at>=start_at and completed_at<end_at group by age_range) grouped)));
  growth:=jsonb_set(growth,'{gender}',public.business_suppress_small_groups((select coalesce(jsonb_agg(jsonb_build_object('label',gender,'users',users)),'[]'::jsonb) from (select gender,count(*) users from public.onboarding_reporting_snapshots where completed_at>=start_at and completed_at<end_at group by gender) grouped)));
  growth:=jsonb_set(growth,'{experience}',public.business_suppress_small_groups((select coalesce(jsonb_agg(jsonb_build_object('label',experience,'users',users)),'[]'::jsonb) from (select experience,count(*) users from public.onboarding_reporting_snapshots where completed_at>=start_at and completed_at<end_at group by experience) grouped)));
  growth:=jsonb_set(growth,'{frustrations}',public.business_suppress_small_groups((select coalesce(jsonb_agg(jsonb_build_object('label',biggest_frustration,'users',users)),'[]'::jsonb) from (select biggest_frustration,count(*) users from public.onboarding_reporting_snapshots where completed_at>=start_at and completed_at<end_at group by biggest_frustration) grouped)));
  growth:=jsonb_set(growth,'{workoutFrequency}',public.business_suppress_small_groups((select coalesce(jsonb_agg(jsonb_build_object('label',workouts_per_week::text,'users',users)),'[]'::jsonb) from (select workouts_per_week,count(*) users from public.onboarding_reporting_snapshots where completed_at>=start_at and completed_at<end_at group by workouts_per_week) grouped)));
  growth:=jsonb_set(growth,'{goals}',public.business_suppress_small_groups((select coalesce(jsonb_agg(jsonb_build_object('label',primary_goal,'users',users)),'[]'::jsonb) from (select primary_goal,count(*) users from public.onboarding_reporting_snapshots where completed_at>=start_at and completed_at<end_at group by primary_goal) grouped)));
  growth:=jsonb_set(growth,'{milestoneThemes}',public.business_suppress_small_groups((select coalesce(jsonb_agg(jsonb_build_object('label',milestone_theme,'users',users)),'[]'::jsonb) from (select milestone_theme,count(*) users from public.onboarding_reporting_snapshots where completed_at>=start_at and completed_at<end_at group by milestone_theme) grouped)));
  growth:=jsonb_set(growth,'{onboardingScreens}',coalesce((select jsonb_agg(jsonb_build_object('label',label,'users',users,'views',views,'exits',greatest(users-cta_users,0),'averageTransitionMs',average_transition_ms) order by first_seen) from (
    select viewed.label,count(distinct viewed.anonymous_id) users,count(*) views,count(distinct cta.anonymous_id) cta_users,min(viewed.occurred_at) first_seen,avg(extract(epoch from (cta.occurred_at-viewed.occurred_at))*1000) filter(where cta.occurred_at>=viewed.occurred_at) average_transition_ms
    from (select anonymous_id,occurred_at,coalesce(properties->>'step',properties->>'screenId','unknown') label from public.product_analytics_events where event_name='onboarding_screen_viewed' and occurred_at>=start_at and occurred_at<end_at) viewed
    left join lateral (select event.anonymous_id,event.occurred_at from public.product_analytics_events event where event.event_name='onboarding_cta_pressed' and event.anonymous_id=viewed.anonymous_id and coalesce(event.properties->>'step',event.properties->>'screenId','unknown')=viewed.label and event.occurred_at>=viewed.occurred_at and event.occurred_at<end_at order by event.occurred_at limit 1) cta on true group by viewed.label
  ) grouped),'[]'::jsonb));
  growth:=jsonb_set(growth,'{exercisePopularity}',coalesce((select jsonb_agg(jsonb_build_object('label',label,'users',users,'analyses',analyses) order by analyses desc) from (select coalesce(session.detected_label,session.corrected_label,'Unknown') label,count(distinct attempt.user_id) users,count(*) analyses from public.analysis_attempts attempt join public.analysis_sessions session on session.id=attempt.session_id where attempt.status in ('complete','partial') and attempt.terminal_at>=start_at and attempt.terminal_at<end_at group by 1 order by analyses desc limit 25) grouped),'[]'::jsonb));
  growth:=jsonb_set(growth,'{analysisOutcomes}',coalesce((select jsonb_agg(jsonb_build_object('label',status,'attempts',attempts)) from (select status,count(*) attempts from public.analysis_attempts where coalesce(terminal_at,updated_at)>=start_at and coalesce(terminal_at,updated_at)<end_at group by status) grouped),'[]'::jsonb));
  growth:=jsonb_set(growth,'{reanalysis}',coalesce((select jsonb_agg(jsonb_build_object('label',kind,'attempts',attempts)) from (select kind,count(*) attempts from public.analysis_attempts where created_at>=start_at and created_at<end_at group by kind) grouped),'[]'::jsonb));
  growth:=jsonb_set(growth,'{firstWeekAnalysisDepth}',coalesce((select jsonb_agg(jsonb_build_object('label',depth,'users',users) order by depth) from (select case when delivered=0 then 'zero' when delivered=1 then 'one' else 'two_or_more' end depth,count(*) users from (select signup.id,count(attempt.id) filter(where attempt.status in ('complete','partial') and attempt.terminal_at<=signup.created_at+interval '7 days' and attempt.terminal_at<end_at) delivered from auth.users signup left join public.analysis_attempts attempt on attempt.user_id=signup.id and attempt.created_at>=signup.created_at where signup.created_at>=start_at and signup.created_at<end_at-interval '7 days' and not exists(select 1 from public.business_test_accounts test where test.user_id=signup.id) and not exists(select 1 from public.creator_memberships membership where membership.user_id=signup.id) group by signup.id) cohorts group by 1) grouped),'[]'::jsonb));
  growth:=jsonb_set(growth,'{revenueCurrencies}',coalesce((select jsonb_agg(jsonb_build_object('label',currency,'gross',gross,'transactions',transactions)) from (select coalesce(currency,'unknown') currency,coalesce(sum(gross_amount),0) gross,count(*) transactions from public.subscription_transactions transaction where environment='PRODUCTION' and coalesce(purchased_at,created_at)>=start_at and coalesce(purchased_at,created_at)<end_at and not exists(select 1 from public.business_test_accounts test where test.user_id=transaction.user_id) group by currency) grouped),'[]'::jsonb));
  return jsonb_set(result,'{growth}',growth);
end $$;

revoke all on function public.get_founder_business_dashboard_v8(text,text,date,date) from public,anon,authenticated;
grant execute on function public.get_founder_business_dashboard_v8(text,text,date,date) to service_role;
