import Link from "next/link";
import type { ReactNode } from "react";
import type { BusinessDashboard, DashboardSection, ReportingWindow } from "@/lib/reporting/contracts";

const sections: [DashboardSection,string][] = [["overview","Overview"],["revenue","Revenue"],["creators","Creators"],["growth","Growth"]];
const windows: [ReportingWindow,string][] = [["24h","Today"],["7d","7 days"],["30d","30 days"],["90d","90 days"],["all","All"]];
const href = (section: DashboardSection) => section === "overview" ? "/admin" : `/admin/${section}`;
export function BusinessDashboardShell({ dashboard, adminEmail, children }: { dashboard: BusinessDashboard; adminEmail: string; children: ReactNode }) {
  const dateValue=(value:string|null)=>value ? value.slice(0,10) : "";
  return <main className="admin-shell"><header className="admin-header"><Link href="/admin" className="admin-brand"><span className="admin-mark">F</span><div><b>Formie</b><small>Founder dashboard</small></div></Link><nav className="admin-nav" aria-label="Dashboard sections">{sections.map(([section,label])=><Link key={section} data-active={dashboard.section===section} href={href(section)}>{label}</Link>)}</nav><div className="admin-account"><span>Production</span><small>{adminEmail}</small><form action="/admin/sign-out" method="post"><button type="submit">Sign out</button></form></div></header><section className="admin-content"><div className="admin-toolbar"><div className="admin-window-filter">{windows.map(([window,label])=><Link key={window} data-active={dashboard.window===window} href={`${href(dashboard.section)}?window=${window}`}>{label}</Link>)}</div><form className="admin-custom-range" method="get" action={href(dashboard.section)}><input type="hidden" name="window" value="custom"/><label>From<input required type="date" name="start" defaultValue={dashboard.window==="custom"?dateValue(dashboard.rangeStart):""}/></label><label>To<input required type="date" name="end" defaultValue={dashboard.window==="custom"?dateValue(dashboard.rangeEnd):""}/></label><button data-active={dashboard.window==="custom"} type="submit">Apply</button></form><small>As of {new Date(dashboard.generatedAt).toLocaleString()}</small></div>{dashboard.alerts.length ? <section className="admin-alerts" aria-label="Data alerts">{dashboard.alerts.map((alert)=><div key={alert.key} data-severity={alert.severity}><b>{alert.severity}</b><span>{alert.message}</span></div>)}</section> : null}{children}</section></main>;
}
